# Generated by Django 4.2.3 on 2023-08-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_mp3file_text_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp3file',
            name='text',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
