# Generated by Django 4.2.3 on 2023-08-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_mp3file_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(default='default.jpg', max_length=64),
        ),
    ]
